### ISSUE TITLE
Some questions about SQDDPG

### ISSUE THREAD

**Issue by Majeriot** [hsvgbkhgbv/SQDDPG#19]
Dear Jianhong:
I'm so honored to read this excellent article which is very helpful for me to start with credit assignment in cooperative multi-agent reinforcement learning. However, unfortunately, I've got some questions about this article. Feel sorry to bother you, I'll appreciate it very much if you could spare some time to answer my questions.
My questions:
#1. How to ensure the game is convex when using Q-value as the character function for the cooperative game?
#2. I don't know how to verify that " Shapley value can theoretically guarantee the convergence to the maximal global value". How to verify that? Maybe I don't know what this sentence actually means or Theorem 1. My understanding for Theorem 1 is the objective to optimize is the maximal but the algorithm SQDDPG can not be guaranteed to converge to the global optimal.
#3. Constructing the ECG involves two stages: in stage 1, an oracle arranges the coalition structure and contracts the cooperation agreements and in stage 2, each agent chooses optimal policy to maximize the social welfare of its coalition. However, in the implementation, I don't know where the oracle is and how the coalition structure is arranged.
It will be so kind of you to answer these three questions which will be so helpful for me and I'll appreciate very much. Thanks a lot!

**Comment by hsvgbkhgbv** [comment]
Hi Majeriot,


Thank you for your interests. I'm very glad to answer your questions. First, I have to say this work is not a perfect work, i.e., there exists lots of room to improve, since this should be the first work that formally applies Shapley value and concepts in cooperative game theory to MARL.

Answers to your questions:
#1. This is a good question, however, I think currently this is difficult to implement in practice. One possible method is infinitely checking the condition of convex game during learning, but this could be time consuming.

#2. Your understanding is correct. SQDDPG cannot guarantee the convergence to the global optimum. The practical problem is almost always non-convex. Similar to the common non-convex optimization problem, this is quite difficult to check it in practice. One possible solution is trying traversing as much as the landscape of parameters, but this is impossible in practice. 

#3. The oracle is only used to formulate the problem (or story) that it gives the confidence to the agents that it is possible to find the solution. In implementation, we neglect this oracle for the conciseness of the algorithm. In my view, you can actually design another agent (of a neural network network architecture) to play the role of this oracle.

The way for credit assignment to success is so long, where credit assignments can lie not only on the spatial axis, but also on the temporal axis. If you think this paper is helpful to you, you can cite it when you publish your paper. 


Best Regards,

Jianhong
